# block_design.template.tcl - Block design for HIL test
# Parameterized by hil_project.py via str.replace()

# Source board PS7 preset
source "{{PRESET_TCL}}"

# Create block design
create_bd_design "system"

# Add Zynq PS — export DDR and FIXED_IO
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
make_bd_intf_pins_external [get_bd_intf_pins ps7/DDR]
make_bd_intf_pins_external [get_bd_intf_pins ps7/FIXED_IO]

# Apply board preset
apply_microzed_preset ps7

# Override for this design
set_property -dict [list \
    CONFIG.PCW_USE_M_AXI_GP0 {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {{{FCLK_MHZ}}} \
    CONFIG.PCW_USE_FABRIC_INTERRUPT {0} \
] [get_bd_cells ps7]

# Add AXI interconnect for AXI3 -> AXI4-Lite protocol conversion
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_ic
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {1}] [get_bd_cells axi_ic]

# Add proc_sys_reset
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst

# Add DUT (module reference to VHDL entity)
create_bd_cell -type module -reference {{DUT_ENTITY}} dut

# Externalize ports (generated by Python from hil.json wiring)
{{EXTERNALIZE_TCL}}

# Clock connections: FCLK_CLK0 -> everything
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins ps7/M_AXI_GP0_ACLK]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins axi_ic/ACLK]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins axi_ic/S00_ACLK]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins axi_ic/M00_ACLK]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins rst/slowest_sync_clk]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins dut/clk]

# Reset connections
connect_bd_net [get_bd_pins ps7/FCLK_RESET0_N] [get_bd_pins rst/ext_reset_in]
connect_bd_net [get_bd_pins rst/interconnect_aresetn] [get_bd_pins axi_ic/ARESETN]
connect_bd_net [get_bd_pins rst/peripheral_aresetn] [get_bd_pins axi_ic/S00_ARESETN]
connect_bd_net [get_bd_pins rst/peripheral_aresetn] [get_bd_pins axi_ic/M00_ARESETN]
connect_bd_net [get_bd_pins rst/peripheral_aresetn] [get_bd_pins dut/rst_n]

# AXI connections: PS (AXI3) -> interconnect -> DUT (AXI4-Lite)
connect_bd_intf_net [get_bd_intf_pins ps7/M_AXI_GP0] [get_bd_intf_pins axi_ic/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins axi_ic/M00_AXI] [get_bd_intf_pins dut/s_axi]

# Assign address
assign_bd_address -target_address_space /ps7/Data [get_bd_addr_segs dut/s_axi/reg0] -range {{AXI_RANGE}} -offset {{AXI_BASE_ADDRESS}}

# Validate and save
validate_bd_design
save_bd_design

puts "Block design created: Zynq PS ({{FCLK_MHZ}} MHz FCLK) + AXI interconnect + {{DUT_ENTITY}} @ {{AXI_BASE_ADDRESS}}"
