# create_project.template.tcl - Create Vivado project for HIL loopback test
# Parameterized by hil_project.py via str.replace()
# Usage: vivado -mode batch -source <generated>.tcl [-tclargs [--debug]]

# --- Template parameters (filled by Python) ---
set project_name  "{{PROJECT_NAME}}"
set build_dir     "{{BUILD_DIR}}"
set part          "{{PART}}"
set sources_tcl   "{{SOURCES_TCL}}"
set gen_hil_tcl   "{{GEN_HIL_TOP_TCL}}"
set block_design_tcl "{{BLOCK_DESIGN_TCL}}"
set base_xdc      "{{BASE_XDC}}"
set debug_xdc     "{{DEBUG_XDC}}"
set hil_top_path  "{{HIL_TOP_PATH}}"
set loopback_out  "{{LOOPBACK_OUT}}"
set loopback_in   "{{LOOPBACK_IN}}"
set extra_lb      "{{EXTRA_LB_PAIRS}}"
set tie_low       "{{TIE_LOW_PORTS}}"
set monitor_pfx   "{{MONITOR_PREFIXES}}"

# Parse --debug flag
set enable_debug 0
if {[lsearch -exact $argv "--debug"] >= 0} {
    set enable_debug 1
}

# Create project
set proj_dir [file join $build_dir vivado_project]
create_project $project_name $proj_dir -part $part -force

# Add VHDL sources (TCL list generated by Python)
source $sources_tcl

update_compile_order -fileset sources_1

# Create block design
source $block_design_tcl

# Generate wrapper (Verilog) and add to project
set bd_file [get_files system.bd]
set wrapper [make_wrapper -files $bd_file -top]
add_files -norecurse $wrapper
update_compile_order -fileset sources_1

# Auto-generate hil_top.vhd from the actual wrapper ports
source $gen_hil_tcl
gen_hil_top $wrapper $hil_top_path $enable_debug $loopback_out $loopback_in $monitor_pfx $extra_lb $tie_low

# Add generated top-level and set as top
add_files -norecurse $hil_top_path
set_property top hil_top [current_fileset]

# Add base constraints
add_files -fileset constrs_1 -norecurse $base_xdc

# DEBUG mode: set generic and add ILA insertion XDC
if {$enable_debug} {
    set_property generic {DEBUG=true} [current_fileset]
    add_files -fileset constrs_1 -norecurse $debug_xdc
    set_property USED_IN {implementation} [get_files [file tail $debug_xdc]]
    puts "=== DEBUG mode enabled: MARK_DEBUG + insert_debug.xdc ==="
}

update_compile_order -fileset sources_1

puts "=== Project created: $project_name ==="
puts "  Part:    $part"
puts "  Top:     hil_top"
puts "  Debug:   $enable_debug"
