# gen_hil_top.tcl - Generate hil_top.vhd from the actual system_wrapper ports
#
# Called after make_wrapper.  Reads the generated Verilog wrapper, extracts
# every port, then emits hil_top.vhd that:
#   - Passes through all ports EXCEPT loopback and monitor ports
#   - Wires loopback output -> loopback input internally
#   - Connects monitor ports to internal signals with MARK_DEBUG
#
# Port classification is driven by hil.json (via template parameters):
#   loopback_out     — prefix for the loopback output port (e.g. "txd")
#   loopback_in      — prefix for the loopback input port  (e.g. "rxd")
#   monitor_prefixes — space-separated prefixes for monitor ports (e.g. "irq mon_")
#
# Usage (from create_project.tcl):
#   source gen_hil_top.tcl
#   gen_hil_top $wrapper_file $output_vhd $enable_debug $lb_out $lb_in $mon_pfx

proc gen_hil_top {wrapper_file output_vhd enable_debug loopback_out loopback_in monitor_prefixes} {

    # --- Parse wrapper ports from Verilog ---
    set fp [open $wrapper_file r]
    set src [read $fp]
    close $fp

    # Collect ports: {direction name msb lsb} or {direction name -1 -1} for scalars
    set ports {}
    # Match: inout [14:0]DDR_0_addr;  or  output txd_0;  or  input rxd_0;
    # Vivado puts NO space between ] and name, so use \s* not \s+
    foreach line [split $src \n] {
        set line [string trim $line]
        # Remove trailing comma/semicolon/paren
        regsub {[,;)\s]+$} $line {} line
        if {[regexp {^\s*(input|output|inout)\s+\[(\d+):(\d+)\]\s*(\w+)} $line -> dir msb lsb name]} {
            lappend ports [list $dir $name $msb $lsb]
        } elseif {[regexp {^\s*(input|output|inout)\s+(\w+)} $line -> dir name]} {
            lappend ports [list $dir $name -1 -1]
        }
    }

    if {[llength $ports] == 0} {
        error "gen_hil_top: no ports parsed from $wrapper_file"
    }

    puts "gen_hil_top: parsed [llength $ports] ports from wrapper"

    # --- Classify ports ---
    # Port classification is driven by hil.json parameters (not hardcoded).
    # Loopback ports match "${prefix}_*" or exact "${prefix}".
    # Monitor ports match any of the monitor_prefixes.
    # Everything else is passthrough (DDR, FIXED_IO, etc.)
    set passthrough {}
    set internal_out {}  ;# monitor/irq ports we capture internally
    set internal_in {}   ;# input ports we drive internally
    set lb_out_name ""   ;# matched loopback output port
    set lb_in_name  ""   ;# matched loopback input port

    foreach p $ports {
        lassign $p dir name msb lsb
        if {[string match "${loopback_out}_*" $name] || $name eq $loopback_out} {
            set lb_out_name $name
        } elseif {[string match "${loopback_in}_*" $name] || $name eq $loopback_in} {
            set lb_in_name $name
        } else {
            set is_monitor 0
            foreach pfx $monitor_prefixes {
                if {[string match "${pfx}*" $name]} {
                    set is_monitor 1
                    break
                }
            }
            if {$is_monitor} {
                lappend internal_out [list $dir $name $msb $lsb]
            } else {
                lappend passthrough [list $dir $name $msb $lsb]
            }
        }
    }

    if {$lb_out_name eq "" || $lb_in_name eq ""} {
        error "gen_hil_top: loopback ports not found in wrapper (expected '${loopback_out}_*' and '${loopback_in}_*')"
    }

    # --- Helper: VHDL type string ---
    proc vhdl_type {msb lsb} {
        if {$msb == -1} {
            return "std_logic"
        } else {
            return "std_logic_vector($msb downto $lsb)"
        }
    }

    # --- Emit VHDL ---
    set out {}
    lappend out "-- ============================================================================="
    lappend out "-- Module:       hil_top"
    lappend out "-- Description:  HIL test top-level — loopback ${lb_out_name} -> ${lb_in_name}"
    lappend out "-- ============================================================================="
    lappend out "-- AUTO-GENERATED by gen_hil_top.tcl from system_wrapper ports."
    lappend out "-- Do not hand-edit — re-run create_project.tcl to regenerate."
    lappend out "-- ============================================================================="
    lappend out ""
    lappend out "library ieee;"
    lappend out "use ieee.std_logic_1164.all;"
    lappend out ""
    lappend out "entity hil_top is"
    lappend out "    generic ("
    lappend out "        DEBUG : boolean := false"
    lappend out "    );"
    lappend out "    port ("

    # Emit passthrough ports
    set last_idx [expr {[llength $passthrough] - 1}]
    for {set i 0} {$i <= $last_idx} {incr i} {
        lassign [lindex $passthrough $i] dir name msb lsb
        set vtype [vhdl_type $msb $lsb]
        # Map Verilog direction to VHDL
        switch $dir {
            inout  {set vdir "inout"}
            input  {set vdir "in   "}
            output {set vdir "out  "}
        }
        set trail [expr {$i < $last_idx ? ";" : ""}]
        # Pad name to 22 chars for alignment
        lappend out [format "        %-22s : %s %s%s" $name $vdir $vtype $trail]
    }

    lappend out "    );"
    lappend out "end entity hil_top;"
    lappend out ""
    lappend out "architecture rtl of hil_top is"
    lappend out ""
    # Derive loopback signal name from the output port (strip _0 suffix)
    set lb_sig "[string trimright $lb_out_name 0123456789_]_loopback"
    regsub {_+loopback$} $lb_sig "_loopback" lb_sig
    lappend out "    signal [format %-22s $lb_sig] : std_logic;"

    # Internal signals for monitor/irq ports
    foreach p $internal_out {
        lassign $p dir name msb lsb
        set sig_name "[string trimright $name 0123456789_]_s"
        # Clean up: mon_tx_state_0 -> mon_tx_state_s
        regsub {_+s$} $sig_name "_s" sig_name
        set vtype [vhdl_type $msb $lsb]
        lappend out "    signal [format %-22s $sig_name] : $vtype;"
    }

    lappend out ""
    lappend out "    attribute MARK_DEBUG : string;"
    lappend out "    attribute MARK_DEBUG of [format %-22s $lb_sig] : signal is \"true\";"

    # MARK_DEBUG on each monitor/irq signal (in declarative region)
    foreach p $internal_out {
        lassign $p dir name msb lsb
        set sig_name "[string trimright $name 0123456789_]_s"
        regsub {_+s$} $sig_name "_s" sig_name
        lappend out "    attribute MARK_DEBUG of [format %-22s $sig_name] : signal is \"true\";"
    }

    lappend out ""
    lappend out "begin"
    lappend out ""
    lappend out "    u_system : entity work.system_wrapper"
    lappend out "        port map ("

    # All passthrough ports: name => name
    foreach p $passthrough {
        lassign $p dir name msb lsb
        lappend out [format "            %-26s => %s," $name $name]
    }

    # Loopback: output drives signal, input reads it
    lappend out [format "            %-26s => %s," $lb_out_name $lb_sig]
    lappend out [format "            %-26s => %s," $lb_in_name  $lb_sig]

    # Monitor/irq ports
    set last_int [expr {[llength $internal_out] - 1}]
    for {set i 0} {$i <= $last_int} {incr i} {
        lassign [lindex $internal_out $i] dir name msb lsb
        set sig_name "[string trimright $name 0123456789_]_s"
        regsub {_+s$} $sig_name "_s" sig_name
        set trail [expr {$i < $last_int ? "," : ""}]
        lappend out [format "            %-26s => %s%s" $name $sig_name $trail]
    }

    lappend out "        );"
    lappend out ""
    lappend out "end architecture rtl;"
    lappend out ""

    # Write file
    set fp [open $output_vhd w]
    puts $fp [join $out \n]
    close $fp

    puts "gen_hil_top: wrote $output_vhd ([llength $passthrough] passthrough, [llength $internal_out] monitor, 1 loopback)"
}
